[package]
name = "fdu"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A disk usage scanner for Linux and macOS"

[features]
allocation-profile = []

[dependencies]
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
rayon = "1.5.1"

[profile.release]
lto = "thin"
incremental = true

[profile.profiling]
inherits = "release"
debug = 1
strip = "none"
