[package]
name = "fdu"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A minimal Linux disk usage scanner"

[dependencies]
libc = "0.2"
rayon = "1.5.1"

[profile.release]
lto = "fat"
codegen-units = 1
incremental = false

[profile.profiling]
inherits = "release"
debug = 1
strip = "none"
